#!/bin/sh

_me=$(realpath "$0")
_dir=$(dirname "$_me")

if [ "$(docker images -q dotbash > /dev/null)" = "" ]; then
    docker build -t dotbash "$_dir"
fi

docker run -it --rm -v "$_dir/../:/opt/dotfiles" -w /opt/dotfiles --name dotbash dotbash "$@"
